name: TagPlugin
main: qucumbah.TagPlugin
version: 1.0
author: qucumbah
api-version: 1.15
commands:
  tagstart:
    description: Start tag game as the hunter
    usage: /tagstart <victimPlayer>
  tagabort:
    description: Abort tag game
    usage: /tagabort
  tagresetborder:
    description: Reset border to original size
    usage: /tagresetborder